// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylotzecdkuomddglgmld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsb3R6ZWNka3VvbWRkZ2xnbWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTYxMjcsImV4cCI6MjA3MzYzMjEyN30.ib6O9s3y0LFZ9eNJJPCPCQxf15xg6zGAehUPDcUGrmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});